package br.feevale.game.client;


import javax.swing.*;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;

public class GamePanel extends javax.swing.JFrame implements Runnable {

    private static final int SPEED = 4;
    private static final int SERVER_PORT = 8181;
    private static final String SERVER_HOST = "localhost";

    Player player;
    PrintWriter writer;
    Socket socket;
    BufferedReader reader;

    boolean keyRight = false;
    boolean keyLeft = false;
    boolean keyUp = false;
    boolean keyDown = false;
    boolean isKeyPressed = false;
    int keyPressed;

    public GamePanel() {
        initComponents();
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GamePanel g = new GamePanel();
                g.connect();
                g.setSize(800, 600);
                g.setVisible(true); //TODO: close on error
                Thread game = new Thread(g);
                game.start();
//                while (true) {
//                    g.receive();
//                }
            }
        });
    }

    private boolean connect() {
        try {
            socket = new Socket(SERVER_HOST, SERVER_PORT);
            writer = new PrintWriter(socket.getOutputStream());
            reader = new BufferedReader(new InputStreamReader(socket.getInputStream()));

            CommunicateThread c = new CommunicateThread(socket);
            c.communicate();
            c.start();
            return true;
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao conectar com o servidor: " + e.getLocalizedMessage());
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened();
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }

            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased();
            }
        });
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened() {
        player = new Player();
        player.setup();
        getContentPane().add(player);
        repaint();
    }

    private void formKeyPressed(java.awt.event.KeyEvent evt) {
        isKeyPressed = true;
        keyPressed = evt.getKeyCode();
        if (isKeyPressDown(evt.getKeyCode())) {
            keyDown = true;
            keyUp = false;
            keyLeft = false;
            keyRight = false;
        } else if (isKeyPressUp(evt.getKeyCode())) {
            keyDown = false;
            keyUp = true;
            keyLeft = false;
            keyRight = false;
        } else if (isKeyPressLeft(evt.getKeyCode())) {
            keyDown = false;
            keyUp = false;
            keyLeft = true;
            keyRight = false;
        } else if (isKeyPressRight(evt.getKeyCode())) {
            keyDown = false;
            keyUp = false;
            keyLeft = false;
            keyRight = true;
        }
    }

    private void formKeyReleased() {
        keyDown = false;
        keyUp = false;
        keyLeft = false;
        keyRight = false;
    }

    private void updateGame() {
        if (keyRight) {
            player.x += SPEED;
            player.move();
        } else if (keyLeft) {
            player.x -= SPEED;
            player.move();
        } else if (keyUp) {
            player.y -= SPEED;
            player.move();
        } else if (keyDown) {
            player.y += SPEED;
            player.move();
        }
        if (isKeyPressed) {
            System.out.println("Apertei a tecla " + keyPressed);
            writer.println(keyPressed);
            writer.flush();
            isKeyPressed = false;
        }
    }

//    private void receive() {
//        try {
//            String receive;
//            while ((receive = reader.readLine()) != null) {
//                System.out.println(receive);
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }

    @Override
    public void run() {
        try {
            while (true) {
                updateGame();
                Thread.sleep(20);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private boolean isKeyPressUp(int keyCode) {
        return keyCode == KeyEvent.VK_UP;
    }

    private boolean isKeyPressDown(int keyCode) {
        return keyCode == KeyEvent.VK_DOWN;
    }

    private boolean isKeyPressLeft(int keyCode) {
        return keyCode == KeyEvent.VK_LEFT;
    }

    private boolean isKeyPressRight(int keyCode) {
        return keyCode == KeyEvent.VK_RIGHT;
    }

}

